# Generated by Django 5.2.17 on 2026-08-17 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='ubicación')),
                ('meter_number', models.CharField(blank=True, max_length=80, verbose_name='número de medidor')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='chat de Telegram')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'nodo',
                'verbose_name_plural': 'nodos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='fecha programada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=12, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='readings.node', verbose_name='nodo')),
            ],
            options={
                'verbose_name': 'programación',
                'verbose_name_plural': 'programaciones',
                'ordering': ['due_date', 'node__code'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_value', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor detectado')),
                ('confirmed_value', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor confirmado')),
                ('ocr_text', models.TextField(blank=True, verbose_name='texto OCR')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='confianza OCR')),
                ('photo', models.ImageField(upload_to='meter_photos/%Y/%m/', verbose_name='fotografía')),
                ('status', models.CharField(choices=[('REVIEW', 'Por confirmar'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Anulada')], default='REVIEW', max_length=12, verbose_name='estado')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_readings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='readings.readingschedule')),
            ],
            options={
                'verbose_name': 'lectura',
                'verbose_name_plural': 'lecturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(verbose_name='fecha de envío')),
                ('chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='readings.readingschedule')),
            ],
            options={
                'verbose_name': 'recordatorio enviado',
                'verbose_name_plural': 'recordatorios enviados',
            },
        ),
        migrations.AddConstraint(
            model_name='readingschedule',
            constraint=models.UniqueConstraint(fields=('node', 'due_date'), name='unique_node_due_date'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('schedule', 'sent_on', 'chat_id'), name='one_reminder_per_day'),
        ),
    ]
