# Generated by Django 5.2.17 on 2026-08-17 15:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='confirmed_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valor confirmado'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='detected_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valor detectado'),
        ),
    ]
