# Generated by Django 5.2.17 on 2026-08-17 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_alter_reading_confirmed_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='billing_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de emisión'),
        ),
        migrations.AddField(
            model_name='node',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de vencimiento'),
        ),
        migrations.AddField(
            model_name='node',
            name='provider',
            field=models.CharField(blank=True, max_length=80, verbose_name='concesionaria'),
        ),
        migrations.AddField(
            model_name='node',
            name='reading_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de lectura'),
        ),
        migrations.AddField(
            model_name='node',
            name='supply_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='número de suministro'),
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de lectura'),
        ),
        migrations.AddField(
            model_name='reading',
            name='source',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('EXCEL', 'Excel'), ('MANUAL', 'Manual')], default='TELEGRAM', max_length=12, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='photo',
            field=models.ImageField(blank=True, upload_to='meter_photos/%Y/%m/', verbose_name='fotografía'),
        ),
    ]
