# Generated by Django 5.2.17 on 2026-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_backfill_reading_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminderlog',
            name='one_reminder_per_day',
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['schedule', 'chat_id', 'sent_at'], name='reminder_cooldown_idx'),
        ),
    ]
