# Generated by Django 5.2.17 on 2026-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_remove_reminderlog_one_reminder_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ocr_learning_generation',
            field=models.PositiveIntegerField(default=1, help_text='Incrementar al reemplazar el medidor o para empezar un aprendizaje nuevo.', verbose_name='versión de aprendizaje del medidor'),
        ),
        migrations.AddField(
            model_name='reading',
            name='ocr_attempts',
            field=models.JSONField(blank=True, default=list, verbose_name='historial de reconocimiento'),
        ),
    ]
