# Generated by Django 5.2.17 on 2026-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_node_ocr_learning_generation_reading_ocr_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='ocr_learning_verified',
            field=models.BooleanField(default=False, help_text='Activar solo después de comparar la fotografía y el valor confirmado, incluyendo decimales.', verbose_name='etiqueta visual verificada para aprendizaje'),
        ),
    ]
