# Generated by Django 5.2.17 on 2026-09-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_exclude_historical_ocr_learning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['code'], 'permissions': [('access_management', 'Ver Gestión de lecturas'), ('access_annual', 'Ver Lecturas WI-NET'), ('access_notifications', 'Ver calendario y notificaciones'), ('access_admin', 'Entrar a Administración')], 'verbose_name': 'nodo', 'verbose_name_plural': 'nodos'},
        ),
    ]
