AUTHORIZED_NODES = [
    {"name": "200 Millas", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Benvenutto", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Guardia Peruana", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Hipolito Unanue", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Los Alamos", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Lince", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Mirables", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Pachacamac", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Salamanca", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "San Pedro", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Santos Chocano", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Sucre", "location": "LIMA", "provider": "PLUZ"},
    {"name": "La Ensenada*", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Caqueta", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Chorrillos II", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Mariategui", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Niño Jesus", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Pelitres", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Pista Nueva", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Punta Hermosa", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Santa Fe", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Santa Rosa", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Villa el Salvador", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Vitarte", "location": "LIMA", "provider": "LUZ DEL SUR"},
    {"name": "Zarate", "location": "LIMA", "provider": "PLUZ"},
    {"name": "Barranca", "location": "PROVINCIA", "provider": "PLUZ"},
    {"name": "Huacho", "location": "PROVINCIA", "provider": "PLUZ"},
    {"name": "Huaral", "location": "PROVINCIA", "provider": "PLUZ"},
    {"name": "Chancay", "location": "PROVINCIA", "provider": "PLUZ"},
    {"name": "Catacaos", "location": "PROVINCIA", "provider": "ENOSA"},
    {"name": "Pimentel", "location": "PROVINCIA", "provider": "ENSA"},
    {"name": "Chimbote Manco Capac", "location": "PROVINCIA", "provider": "HIDRANDINA"},
    {"name": "Chimbote Las Palmeras", "location": "PROVINCIA", "provider": "HIDRANDINA"},
]

